<?php
// $Id: wurfl_imagecache_ui.module,v 1.30 2009/03/31 03:11:26 drewish Exp $

/**
 * Administrative interface to wurfl_imagecache.
 *
 */

/**
 * Implementation of hook_help().
 */
function wurfl_imagecache_ui_help($path, $arg) {
  switch($path) {
    case 'admin/build/wurfl_imagecache':
      return t('Manage wurfl_ImageCache presets.');
    case 'admin/build/wurfl_imagecache/%/export':
      return t('Place the following snippet in your module as part of <code>hook_wurfl_imagecache_default_presets()</code>.');
  }
}

/**
 * Implementation of hook_menu().
 */
function wurfl_imagecache_ui_menu() {
  $items = array();
  $items['admin/build/wurfl_imagecache'] = array(
    'title' => 'wurfl_ImageCache',
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'description' => 'Administer wurfl_imagecache presets and actions.',
    'page callback' => 'wurfl_imagecache_ui_preset_overview',
    'access arguments' => array('administer wurfl_imagecache'),
  );
  $items['admin/build/wurfl_imagecache/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/build/wurfl_imagecache/add'] = array(
    'title' => 'Add new preset',
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_add_form'),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Edit preset: !presetname', 3),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_form', 3),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/delete'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Delete preset: !presetname', 3),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_delete_form', 3),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/flush'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Flush preset: !presetname', 3),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_flush_form', 3),
    'access arguments' => array('flush wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/export'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Export preset: !presetname', 3),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_export_form', 3),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/override'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Override preset: !presetname', 3),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_preset_form', 3, TRUE),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/add/%'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Add !actionname to !presetname', 3, 5),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_action_add_form', 3, 5),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/%wurfl_imagecache_action'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('!action for preset !presetname', 3, 4),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_action_form', 3, 4),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/wurfl_imagecache/%wurfl_imagecache_ui_preset/%wurfl_imagecache_action/delete'] = array(
    'title callback' => 'wurfl_imagecache_preset_title_callback',
    'title arguments' => array('Delete !action for preset !presetname', 3, 4),
    'file' => 'wurfl_imagecache_ui.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wurfl_imagecache_ui_action_delete_form', 3, 4),
    'access arguments' => array('administer wurfl_imagecache'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu wildcard loader.
 */
function wurfl_imagecache_ui_preset_load($preset_id) {
  return wurfl_imagecache_preset($preset_id, TRUE);
}

function wurfl_imagecache_preset_title_callback($title, $preset = array(), $action = array()) {
  $replacements = array();
  if (!empty($preset)) {
    $replacements['!presetname'] = $preset['presetname'];
    $replacements['!presetid'] = $preset['presetid'];
  }
  if (!empty($action) && !is_array($action)) {
    $replacements['!actionname'] = $action;
  }
  elseif (!empty($action)) {
    $replacements['!action'] = $action['action'];
  }
  return t($title, $replacements);
}

/**
 * Implementation of hook_theme().
 */
function wurfl_imagecache_ui_theme() {
  return array(
    'wurfl_imagecache_ui_preset_actions' => array(
      'arguments' => array(
        'form' => NULL,
      ),
      'file' => 'wurfl_imagecache_ui.pages.inc',
    ),
  );
}

